import type {
  AlertaVencimientoSanidad,
  EventoSanitarioRegistro,
  ProximaAplicacionSanitaria,
} from "@/domain/sanidad";

/** Histórico de aplicaciones registradas — demo ciclo completo. */
export const MOCK_EVENTOS_SANIDAD: EventoSanitarioRegistro[] = [
  {
    id: "san-901",
    caravana: "UY 884 102 045",
    tipo: "vacuna",
    producto: "Coglavax 10",
    dosis: "2 ml SC",
    fecha: "2026-05-02",
    lotePotrero: "Lote Mater — Potrero 4",
    responsable: "MV Ana Martínez",
    observaciones: "Temperatura 18 °C estable; marca legible.",
  },
  {
    id: "san-902",
    caravana: "UY 993 401 112",
    tipo: "antiparasitario",
    producto: "Iverm + closantel (formula campo)",
    dosis: "1 ml / 20 kg PV",
    fecha: "2026-04-28",
    lotePotrero: "Terminación Alfa — Norte",
    responsable: "Pablo Dutra",
    observaciones: "Revisar parásitos externos en D+21.",
  },
  {
    id: "san-903",
    caravana: "AR 12 0044 019",
    tipo: "vacuna",
    producto: "Respiratorio 3‑vías (viral)",
    dosis: "2 ml IM",
    fecha: "2026-04-20",
    lotePotrero: "Cría — Vaquillonas norte",
    responsable: "MV Ana Martínez",
  },
  {
    id: "san-904",
    caravana: "UY 661 002 901",
    tipo: "tratamiento",
    producto: "Ceftiofur sódico",
    dosis: "8 mg/kg cada 72 h × 3",
    fecha: "2026-05-01",
    lotePotrero: "Torete — aislamiento 2",
    responsable: "Laura Quinteros",
    observaciones: "Retiros según etiqueta hasta el 09/05.",
  },
  {
    id: "san-905",
    caravana: "UY 774 102 233",
    tipo: "enfermedad",
    producto: "Diagnóstico clínico mastitis NO TRATADA IA",
    dosis: "—",
    fecha: "2026-03-30",
    lotePotrero: "Recría Este — Sector 12",
    responsable: "MV Claudia Oribe",
    observaciones: "Muestreo lácteos negativo posterior.",
  },
  {
    id: "san-906",
    caravana: "UY 993 901 204",
    tipo: "vacuna",
    producto: "Clostridiales refuerzo",
    dosis: "5 ml SC",
    fecha: "2026-04-10",
    lotePotrero: "Terminación Beta — Sur",
    responsable: "Pablo Dutra",
    observaciones: "Ventana próximos 15–20 días (ver calendario).",
  },
  {
    id: "san-907",
    caravana: "AR 12 0099 021",
    tipo: "antiparasitario",
    producto: "Moxidectina (oral)",
    dosis: "0,6 ml / 10 kg PV",
    fecha: "2026-04-18",
    lotePotrero: "Recría — Terneros desmamados",
    responsable: "Laura Quinteros",
  },
  {
    id: "san-908",
    caravana: "UY 884 009 332",
    tipo: "vacuna",
    producto: "Brucella abortus RB51 (según programa)",
    dosis: "Dosis oficial",
    fecha: "2026-02-12",
    lotePotrero: "Lote Mater — Potrero 7",
    responsable: "Sanidad establecimiento",
    observaciones: "Registro SIOV cargado día posterior.",
  },
  {
    id: "san-909",
    caravana: "UY 661 003 444",
    tipo: "tratamiento",
    producto: "Penicilina G benzatínica — preventivo podal",
    dosis: "20.000 IU/kg única",
    fecha: "2026-03-06",
    lotePotrero: "Servicio campo — Rodeo norte",
    responsable: "MV Claudia Oribe",
  },
];

export const MOCK_PROXIMAS_SANIDAD: ProximaAplicacionSanitaria[] = [
  {
    id: "prx-01",
    fechaProgramada: "2026-05-11",
    tipo: "vacuna",
    titulo: "Refuerzo clostridiales — rodeo materno",
    lotePotrero: "Lote Mater — Potrero 7",
    notas: "Coordinar con movilidad sala el 09/05.",
  },
  {
    id: "prx-02",
    fechaProgramada: "2026-05-12",
    tipo: "vacuna",
    titulo: "Respiratorio 2ª dosis terminación Alfa",
    lotePotrero: "Terminación Alfa — Centro",
    notas: "6 animales marcados campo sin chip visible.",
  },
  {
    id: "prx-03",
    fechaProgramada: "2026-05-14",
    tipo: "antiparasitario",
    titulo: "Desparasitación estratégica primavera Recría Oeste",
    lotePotrero: "Recría Oeste — Secano",
  },
  {
    id: "prx-04",
    fechaProgramada: "2026-05-14",
    tipo: "tratamiento",
    titulo: "Control día 10 post‑primer dosis antimicrobiano (toro 661002901)",
    caravana: "UY 661 002 901",
    notas: "Evaluar mejoría podal antes de alta.",
  },
  {
    id: "prx-05",
    fechaProgramada: "2026-05-18",
    tipo: "vacuna",
    titulo: "Leptospirosis + refuerzos cría tardía",
    lotePotrero: "Cría — Parición tardía",
  },
  {
    id: "prx-06",
    fechaProgramada: "2026-05-22",
    tipo: "enfermedad",
    titulo: "Torneo sanitario oficial — marca brucela",
    lotePotrero: "Lote Mater — Potrero 2",
    notas: "Checklist papel + tablet.",
  },
  {
    id: "prx-07",
    fechaProgramada: "2026-06-02",
    tipo: "vacuna",
    titulo: "Programa Carbunco hemático segundo turno terminación Beta",
    lotePotrero: "Terminación Beta — Sur",
  },
];

/** Alertas de vencimiento / períodos finales — solo UI demo. */
export const MOCK_ALERTAS_VENCIMIENTOS: AlertaVencimientoSanidad[] = [
  {
    id: "alv-01",
    severidad: "critical",
    tipo: "retiro_carne",
    titulo: "Fin retiro carnes — tratamiento antimicrobiano",
    detalle:
      "UY 661 002 901 (toro aislamiento) — libera movilización carne después del último día de retiro confirmado.",
    fechaLimite: "2026-05-09",
    referenciaCaravana: "UY 661 002 901",
  },
  {
    id: "alv-02",
    severidad: "warning",
    tipo: "retiro_lacteos",
    titulo: "Ventana lácteos post mastitis tratada",
    detalle:
      "Holando Lote Mater 2 — retiro lácteos programado hasta 14/05 según primera aplicación 02/05.",
    fechaLimite: "2026-05-14",
    referenciaLote: "Lote Mater — Potrero 2",
  },
  {
    id: "alv-03",
    severidad: "warning",
    tipo: "vacuna_plan",
    titulo: "Caducidad lote vacuum frigorífico móvil",
    detalle: "Cadena frío equipo móvil: revisar registros antes de campaña RB51.",
    fechaLimite: "2026-05-20",
  },
  {
    id: "alv-04",
    severidad: "info",
    tipo: "renov_certificado",
    titulo: "Vencimiento certificado establecimiento DTe",
    detalle:
      "Trámites administrativos sanitarios — cargar nueva documentación ante organismo oficial.",
    fechaLimite: "2026-07-08",
  },
  {
    id: "alv-05",
    severidad: "warning",
    tipo: "medicacion",
    titulo: "Reposición tratamiento soporte — stock ivermectina",
    detalle:
      "Inventario marca fin de período económico; pedido sugerido 10 días antes del agotamiento previsto.",
    fechaLimite: "2026-05-26",
    referenciaLote: "Farmacia campo",
  },
];
