import type { Animal } from "@/domain/animal";

/** Dataset demo — ciclo completo (cría, recría, terminación). */
export const MOCK_ANIMALES: Animal[] = [
  {
    id: "rm-884102045",
    caravana: "UY 884 102 045",
    categoria: "vaca",
    raza: "Angus",
    sexo: "H",
    fechaNacimiento: "2019-06-21",
    pesoActualKg: 582,
    gdpKgDia: 0.18,
    estadoSanitario: "al_día",
    estadoReproductivo: "preñada",
    lotePotrero: "Lote Mater — Potrero 4",
    historial: [
      {
        id: "ev-001",
        fecha: "2026-05-08",
        tipo: "reproduccion",
        titulo: "Ecografía positiva (~90 días)",
        detalle: "Servicio IA 06/02. Próximo control 18/06.",
      },
      {
        id: "ev-002",
        fecha: "2026-04-12",
        tipo: "sanidad",
        titulo: "Vacuna clostridiaceae",
        detalle: "Dosis revisada; sin reacciones.",
      },
      {
        id: "ev-003",
        fecha: "2026-02-28",
        tipo: "pesaje",
        titulo: "Pesaje en sala",
        detalle: "Peso vivo 582 kg (+12 kg sobre anterior).",
      },
    ],
  },
  {
    id: "rm-993401112",
    caravana: "UY 993 401 112",
    categoria: "novillo",
    raza: "Angus × Hereford",
    sexo: "M",
    fechaNacimiento: "2024-07-03",
    pesoActualKg: 392,
    gdpKgDia: 1.14,
    estadoSanitario: "al_día",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Terminación Alfa — Norte",
    historial: [
      {
        id: "ev-010",
        fecha: "2026-05-05",
        tipo: "movimiento",
        titulo: "Ingreso a terminación",
        detalle: "Desde recría B; ración aumentada gradualmente.",
      },
      {
        id: "ev-011",
        fecha: "2026-04-20",
        tipo: "sanidad",
        titulo: "Desparasitación externa/interna",
        detalle: "Peso medio del lote estable.",
      },
    ],
  },
  {
    id: "rm-120044019",
    caravana: "AR 12 0044 019",
    categoria: "ternero",
    raza: "Brahman cruz.",
    sexo: "M",
    fechaNacimiento: "2026-03-09",
    pesoActualKg: 142,
    gdpKgDia: 0.96,
    estadoSanitario: "pendiente_vacunar",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Cría — Vaquillonas norte",
    historial: [
      {
        id: "ev-020",
        fecha: "2026-05-06",
        tipo: "pesaje",
        titulo: "Pesaje campo",
        detalle: "+18 kg desde marcas al nacer.",
      },
      {
        id: "ev-021",
        fecha: "2026-04-15",
        tipo: "sanidad",
        titulo: "Vitaminado A+D+E",
      },
    ],
  },
  {
    id: "rm-774102233",
    caravana: "UY 774 102 233",
    categoria: "vaquillona",
    raza: "Hereford",
    sexo: "H",
    fechaNacimiento: "2025-05-02",
    pesoActualKg: 356,
    gdpKgDia: 0.88,
    estadoSanitario: "al_día",
    estadoReproductivo: "servida",
    lotePotrero: "Recría Este — Sector 12",
    historial: [
      {
        id: "ev-030",
        fecha: "2026-04-30",
        tipo: "reproduccion",
        titulo: "Servicio IA (1º)",
      },
      {
        id: "ev-031",
        fecha: "2026-03-03",
        tipo: "sanidad",
        titulo: "Brucelosis / campaña",
      },
    ],
  },
  {
    id: "rm-661002901",
    caravana: "UY 661 002 901",
    categoria: "toro",
    raza: "Angus",
    sexo: "M",
    fechaNacimiento: "2021-10-29",
    pesoActualKg: 834,
    gdpKgDia: -0.04,
    estadoSanitario: "en_tratamiento",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Torete — aislamiento 2",
    historial: [
      {
        id: "ev-040",
        fecha: "2026-05-02",
        tipo: "sanidad",
        titulo: "Tratamiento podal (ceftiofur)",
        detalle: "Retiro lácteos hasta el 09/05. Control diario.",
      },
      {
        id: "ev-041",
        fecha: "2026-01-09",
        tipo: "movimiento",
        titulo: "Traslado a aislamiento",
      },
    ],
  },
  {
    id: "rm-884201018",
    caravana: "UY 884 201 018",
    categoria: "vaca",
    raza: "Holando",
    sexo: "H",
    fechaNacimiento: "2018-04-08",
    pesoActualKg: 548,
    gdpKgDia: 0.06,
    estadoSanitario: "periodo_retiro",
    estadoReproductivo: "post_parto",
    lotePotrero: "Lote Mater — Potrero 2",
    historial: [
      {
        id: "ev-050",
        fecha: "2026-04-02",
        tipo: "sanidad",
        titulo: "Antiinflamatorio + antibiótico (mastitis)",
        detalle: "Retiro lácteos 12 días desde aplicación.",
      },
      {
        id: "ev-051",
        fecha: "2026-03-18",
        tipo: "reproduccion",
        titulo: "Parto (ternero macho vivo)",
      },
    ],
  },
  {
    id: "rm-993500778",
    caravana: "UY 993 500 778",
    categoria: "novillo",
    raza: "Angus",
    sexo: "M",
    fechaNacimiento: "2024-02-02",
    pesoActualKg: 436,
    gdpKgDia: 1.22,
    estadoSanitario: "al_día",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Terminación Alfa — Centro",
    historial: [
      {
        id: "ev-060",
        fecha: "2026-05-07",
        tipo: "pesaje",
        titulo: "Pesaje de control",
      },
      {
        id: "ev-061",
        fecha: "2026-01-11",
        tipo: "movimiento",
        titulo: "Mezcla lote Alfa-Centro",
      },
    ],
  },
  {
    id: "rm-120088044",
    caravana: "AR 12 0088 044",
    categoria: "ternero",
    raza: "Angus",
    sexo: "M",
    fechaNacimiento: "2026-03-08",
    pesoActualKg: 156,
    gdpKgDia: 0.82,
    estadoSanitario: "pendiente_vacunar",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Cría — Parición tardía",
    historial: [
      {
        id: "ev-070",
        fecha: "2026-05-01",
        tipo: "movimiento",
        titulo: "Identificación oficial",
      },
      {
        id: "ev-071",
        fecha: "2026-04-30",
        tipo: "sanidad",
        titulo: "Colostro control / refuerzo",
      },
    ],
  },
  {
    id: "rm-774300511",
    caravana: "UY 774 300 511",
    categoria: "vaquillona",
    raza: "Brangus",
    sexo: "H",
    fechaNacimiento: "2025-08-11",
    pesoActualKg: 312,
    gdpKgDia: 0.91,
    estadoSanitario: "al_día",
    estadoReproductivo: "vacia",
    lotePotrero: "Recría Oeste — Secano",
    historial: [
      {
        id: "ev-080",
        fecha: "2026-04-17",
        tipo: "pesaje",
        titulo: "Pesaje recría",
      },
    ],
  },
  {
    id: "rm-884009332",
    caravana: "UY 884 009 332",
    categoria: "vaca",
    raza: "Angus",
    sexo: "H",
    fechaNacimiento: "2017-11-12",
    pesoActualKg: 524,
    gdpKgDia: 0.11,
    estadoSanitario: "al_día",
    estadoReproductivo: "vacia",
    lotePotrero: "Lote Mater — Potrero 7",
    historial: [
      {
        id: "ev-090",
        fecha: "2026-03-24",
        tipo: "reproduccion",
        titulo: "Diagnóstico vacía (60 días)",
      },
      {
        id: "ev-091",
        fecha: "2026-02-14",
        tipo: "sanidad",
        titulo: "Vacuna respiratoria",
      },
    ],
  },
  {
    id: "rm-993901204",
    caravana: "UY 993 901 204",
    categoria: "novillo",
    raza: "Hereford",
    sexo: "M",
    fechaNacimiento: "2023-12-12",
    pesoActualKg: 468,
    gdpKgDia: 1.08,
    estadoSanitario: "pendiente_vacunar",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Terminación Beta — Sur",
    historial: [
      {
        id: "ev-100",
        fecha: "2026-05-04",
        tipo: "sanidad",
        titulo: "Recordatorio: refuerzo clostridiales",
      },
    ],
  },
  {
    id: "rm-661003444",
    caravana: "UY 661 003 444",
    categoria: "toro",
    raza: "Brahman",
    sexo: "M",
    fechaNacimiento: "2020-01-06",
    pesoActualKg: 798,
    gdpKgDia: -0.11,
    estadoSanitario: "al_día",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Servicio campo — Rodeo norte",
    historial: [
      {
        id: "ev-110",
        fecha: "2026-03-06",
        tipo: "sanidad",
        titulo: "Examen reproductivo (movilidad)",
      },
    ],
  },
  {
    id: "rm-120099021",
    caravana: "AR 12 0099 021",
    categoria: "ternero",
    raza: "Cruzado",
    sexo: "M",
    fechaNacimiento: "2026-01-07",
    pesoActualKg: 218,
    gdpKgDia: 0.79,
    estadoSanitario: "al_día",
    estadoReproductivo: "no_aplica",
    lotePotrero: "Recría — Terneros desmamados",
    historial: [
      {
        id: "ev-120",
        fecha: "2026-04-18",
        tipo: "sanidad",
        titulo: "Vacuna respiratorio + clostridiales",
      },
      {
        id: "ev-121",
        fecha: "2026-04-01",
        tipo: "movimiento",
        titulo: "Destete y mezcla lote RD-12",
      },
    ],
  },
];
