import type { EventoReproductivoRegistro } from "@/domain/reproduccion";

/** Eventos reproductivos — establecimiento ciclo completo (demo). */
export const MOCK_EVENTOS_REPRODUCCION: EventoReproductivoRegistro[] = [
  {
    id: "rep-001",
    caravanaHembra: "UY 884 102 045",
    tipo: "diagnostico_prenez",
    fecha: "2026-05-08",
    toroSemen: "IA — pajuela Angus A14",
    resultado: "positivo",
    fechaProbableParto: "2027-02-18",
    lotePotrero: "Lote Mater — Potrero 4",
    observaciones: "Ecografía ~90 días; servicio registrado 06/02.",
  },
  {
    id: "rep-002",
    caravanaHembra: "UY 774 102 233",
    tipo: "inseminacion",
    fecha: "2026-04-30",
    toroSemen: "Semen Hereford lot H77",
    resultado: "pendiente",
    fechaProbableParto: "2027-02-07",
    lotePotrero: "Recría Este — Sector 12",
    observaciones: "1.er servicio temporada; control ecográfico 25/06.",
  },
  {
    id: "rep-003",
    caravanaHembra: "UY 884 009 332",
    tipo: "diagnostico_prenez",
    fecha: "2026-03-24",
    toroSemen: "Monta toro campo RN3",
    resultado: "negativo",
    lotePotrero: "Lote Mater — Potrero 7",
    observaciones: "60 días post‑servicio; reprogramar.",
  },
  {
    id: "rep-004",
    caravanaHembra: "UY 884 201 018",
    tipo: "parto",
    fecha: "2026-03-18",
    toroSemen: "Monta anterior temporada",
    resultado: "positivo",
    fechaProbableParto: "2026-03-18",
    lotePotrero: "Lote Mater — Potrero 2",
    observaciones: "Macho vivo 38 kg; APGAR ok.",
  },
  {
    id: "rep-005",
    caravanaHembra: "UY 774 300 511",
    tipo: "servicio",
    fecha: "2026-05-02",
    toroSemen: "Toro IA sincronizada — pajuela Brangus B02",
    resultado: "pendiente",
    lotePotrero: "Recría Oeste — Secano",
    observaciones: "Protocolo ov‑sinc + dispositivo CIDR.",
  },
  {
    id: "rep-006",
    caravanaHembra: "AR 12 0088 044",
    tipo: "servicio",
    fecha: "2026-04-22",
    toroSemen: "Monta toro control terneros",
    resultado: "pendiente",
    lotePotrero: "Cría — Parición tardía",
    observaciones: "Vaquillona primer servicio.",
  },
  {
    id: "rep-007",
    caravanaHembra: "UY 993 901 204",
    tipo: "aborto",
    fecha: "2026-02-28",
    toroSemen: "Gestación IA — lote terminación",
    resultado: "negativo",
    lotePotrero: "Terminación Beta — Sur",
    observaciones: "Aborto espontáneo ~120 días; muestra enviada.",
  },
  {
    id: "rep-008",
    caravanaHembra: "UY 884 102 045",
    tipo: "inseminacion",
    fecha: "2026-02-06",
    toroSemen: "IA — pajuela Angus A14",
    resultado: "positivo",
    fechaProbableParto: "2027-02-18",
    lotePotrero: "Lote Mater — Potrero 4",
    observaciones: "Servicio que originó la gestación confirmada en rep-001.",
  },
  {
    id: "rep-009",
    caravanaHembra: "UY 884 009 332",
    tipo: "servicio",
    fecha: "2026-01-15",
    toroSemen: "Toro Angus RN‑campo",
    resultado: "pendiente",
    lotePotrero: "Lote Mater — Potrero 7",
    observaciones: "Monta natural seguimiento 45 días.",
  },
  {
    id: "rep-010",
    caravanaHembra: "UY 774 102 233",
    tipo: "diagnostico_prenez",
    fecha: "2026-03-12",
    toroSemen: "Seguimiento IA Feb",
    resultado: "negativo",
    lotePotrero: "Recría Este — Sector 12",
    observaciones: "Ecografía vacía; nueva IA abril.",
  },
  {
    id: "rep-011",
    caravanaHembra: "UY 884 102 045",
    tipo: "parto",
    fecha: "2025-08-04",
    toroSemen: "Campo anterior",
    resultado: "positivo",
    fechaProbableParto: "2025-08-04",
    lotePotrero: "Lote Mater — Potrero 4",
    observaciones: "Hembra ternera hembra 34 kg.",
  },
  {
    id: "rep-012",
    caravanaHembra: "AR 12 0044 019",
    tipo: "servicio",
    fecha: "2026-05-09",
    toroSemen: "No aplica — menor edad registro",
    resultado: "pendiente",
    lotePotrero: "Cría — Vaquillonas norte",
    observaciones: "Registro administrativo de segregación reproductiva.",
  },
  {
    id: "rep-013",
    caravanaHembra: "UY 774 300 511",
    tipo: "diagnostico_prenez",
    fecha: "2026-04-05",
    toroSemen: "Seguimiento monta otoño",
    resultado: "positivo",
    fechaProbableParto: "2027-01-22",
    lotePotrero: "Recría Oeste — Secano",
    observaciones: "Palpación 45 días — gestación activa.",
  },
  {
    id: "rep-015",
    caravanaHembra: "UY 884 009 332",
    tipo: "parto",
    fecha: "2026-05-03",
    toroSemen: "Gestación — servicio 2025",
    resultado: "positivo",
    fechaProbableParto: "2026-05-03",
    lotePotrero: "Lote Mater — Potrero 7",
    observaciones: "Macho vivo 40 kg; dip neonatal aplicado.",
  },
  {
    id: "rep-014",
    caravanaHembra: "UY 884 201 018",
    tipo: "diagnostico_prenez",
    fecha: "2026-03-01",
    toroSemen: "IA — lactancia controlada",
    resultado: "positivo",
    fechaProbableParto: "2026-11-28",
    lotePotrero: "Lote Mater — Potrero 2",
    observaciones: "Ecografía previa a plan de secado.",
  },
];
